services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/pulse-backend
    volumes:
      - ./pulse-backend:/app/pulse-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery-worker:
    build: .   
    command: celery -A celery_app worker --loglevel=info --concurrency=2
    working_dir: /app/pulse-backend
    volumes:
      - ./pulse-backend:/app/pulse-backend
    restart: always
    env_file:
      - .env

  celery-beat:
    build: .   
    command: celery -A celery_app beat --loglevel=info
    working_dir: /app/pulse-backend
    volumes:
      - ./pulse-backend:/app/pulse-backend
    depends_on:
      - celery-worker
    restart: always
    env_file:
      - .env
